/* Standalone browser script: no imports, bundler, or local web server required. */
(() => {
  const legacy = [
    ['j1','junior','word','apple','りんご'],['j2','junior','word','important','重要な'],['j3','junior','word','beautiful','美しい'],['j4','junior','word','environment','環境'],['j5','junior','word','different','異なる'],['j6','junior','word','practice','練習する'],['j7','junior','word','usually','たいてい'],['j8','junior','word','promise','約束'],['j9','junior','word','history','歴史'],['j10','junior','word','language','言語'],['j11','junior','word','prepare','準備する'],['j12','junior','word','explain','説明する'],['j13','junior','word','receive','受け取る'],['j14','junior','word','especially','特に'],['j15','junior','word','choose','選ぶ'],['j16','junior','word','future','未来'],['j17','junior','word','country','国'],['j18','junior','word','member','メンバー'],['j19','junior','word','necessary','必要な'],['j20','junior','word','continue','続ける'],
    ['jp1','junior','phrase','look for','〜を探す'],['jp2','junior','phrase','be interested in','〜に興味がある'],['jp3','junior','phrase','take care of','〜の世話をする'],['jp4','junior','phrase','be good at','〜が得意'],['jp5','junior','phrase','for example','たとえば'],['jp6','junior','phrase','have to','〜しなければならない'],
    ['s1','senior','word','available','利用できる'],['s2','senior','word','increase','増加する'],['s3','senior','word','benefit','利益・恩恵'],['s4','senior','word','require','必要とする'],['s5','senior','word','evidence','証拠'],['s6','senior','word','consider','考慮する'],['s7','senior','word','opportunity','機会'],['s8','senior','word','prevent','防ぐ'],
    ['sp1','senior','phrase','as a result','結果として'],['sp2','senior','phrase','in addition to','〜に加えて'],['sp3','senior','phrase','be responsible for','〜に責任がある'],['sp4','senior','phrase','deal with','〜に対処する'],['sp5','senior','phrase','take advantage of','〜を利用する'],['sp6','senior','phrase','in spite of','〜にもかかわらず']
  ];
  const fallback = legacy.map(([id,level,type,english,japanese]) => ({id,level,type,english,japanese,example:`I learned the word "${english}" today.`,exampleJapanese:`今日は「${english}」を学習しました。`}));
  const catalog = window.EnglishCardCatalog || [];
  const catalogKeys = new Set(catalog.map(q => `${q.type}:${q.english.toLowerCase()}`));
  const Q = [...fallback, ...catalog.filter(q => !catalogKeys.has(`missing:${q.english}`) && !fallback.some(f => f.type === q.type && f.english.toLowerCase() === q.english.toLowerCase()))];
  const $ = s => document.querySelector(s), app = $('#app'), KEY = 'englishCardApp_v1';
  const DEF = {'1':10,'2':7,'3':5,'4':3,'5plus':2};
  const DIR = {enJa:{name:'英和カード',flow:'英語 → 日本語',prompt:'英語',answer:'日本語'},jaEn:{name:'和英カード',flow:'日本語 → 英語',prompt:'日本語',answer:'英語'}};
  const emptyScope = () => ({histories:{},reviewQueue:[],sessions:{}});
  const init = () => ({version:2,settings:{reviewIntervals:{...DEF}},directions:{enJa:emptyScope(),jaEn:emptyScope()}});
  const migrate = saved => {
    const base = init();
    if (!saved || typeof saved !== 'object') return base;
    base.settings.reviewIntervals = {...DEF,...(saved.settings?.reviewIntervals || {})};
    if (saved.directions) {
      for (const d of Object.keys(DIR)) base.directions[d] = {...emptyScope(),...(saved.directions[d] || {})};
      return base;
    }
    base.directions.enJa = {histories:saved.histories || {},reviewQueue:saved.reviewQueue || [],sessions:saved.sessions || {}};
    return base;
  };
  let state;
  try { state = migrate(JSON.parse(localStorage.getItem(KEY) || 'null')); } catch { state = init(); }
  const save = () => localStorage.setItem(KEY, JSON.stringify(state));
  const scope = d => state.directions[d];
  const qs = (l,c='both') => Q.filter(q => q.level === l && (c === 'both' || q.type === c));
  const qid = id => Q.find(q => q.id === id);
  const sessionKey = (l,c) => `${l}:${c}`;
  const ln = l => l === 'junior' ? '中学' : '高校';
  const cn = c => ({word:'英単語',phrase:'英熟語',both:'英単語＋英熟語'})[c];
  const btn = (text, cls='btn', attrs='') => `<button class="${cls}" ${attrs}>${text}</button>`;
  const draw = html => app.innerHTML = html;
  const makeSession = (level,category) => ({level,category,consecutiveReviewCount:0,studyMode:'normal',current:null,sessionStats:{cards:0,newCards:0,reviewCards:0,learnedFirstTry:0,learnedTwoTries:0,learnedThreePlus:0},startedAt:new Date().toISOString()});
  const speak = text => { if (!('speechSynthesis' in window)) return alert('このブラウザは音声再生に対応していません。'); window.speechSynthesis.cancel(); const u = new SpeechSynthesisUtterance(text); u.lang = 'en-US'; u.rate = .85; window.speechSynthesis.speak(u); };
  const nativeAnchorClick = HTMLAnchorElement.prototype.click;
  HTMLAnchorElement.prototype.click = function() { if (this.download && !this.isConnected) { document.body.append(this); setTimeout(() => this.remove(), 0); } return nativeAnchorClick.call(this); };
  const progress = (d,l,c) => { const all = qs(l,c), histories = scope(d).histories, studied = all.filter(q => histories[q.id]?.firstStudied).length; return {total:all.length,studied,unstudied:all.length-studied,pct:all.length ? Math.round(studied / all.length * 100) : 0}; };
  let active = {};

  function home() { active = {}; draw(`<section class="screen panel home-panel"><button class="settings-button" id="set" type="button" aria-label="設定">⚙</button><h1>英和・和英カード</h1><p class="lead">くり返し学習で、英語を自分のものに。</p><div class="stack">${btn('学習','btn btn-primary','id="start"')}${btn('復習','btn btn-retry','id="weak"')}${btn('進捗確認','btn','id="prog"')}${btn('苦手問題出力','btn btn-outline','id="export"')}</div></section>`); $('#start').onclick = () => directions('study'); $('#weak').onclick = () => directions('weak'); $('#export').onclick = weakExport; $('#prog').onclick = () => directions('prog'); $('#set').onclick = settings; }
  const weakRows = level => Object.entries(DIR).flatMap(([direction,info]) => Object.values(scope(direction).histories).filter(h => h.retryCount > 0).map(h => ({q:qid(h.questionId),h,direction,info})).filter(x => x.q && (level === 'all' || x.q.level === level))).sort((a,b) => b.h.retryCount-a.h.retryCount || a.q.english.localeCompare(b.q.english));
  function weakExport() { let level='all'; const render=()=>{const labels={all:'全苦手問題',junior:'中学苦手問題',senior:'高校苦手問題'},count=weakRows(level).length;draw(`<section class="screen panel"><button class="back" id="back">← 戻る</button><h2>苦手問題を出力</h2><p class="muted">出力する範囲と形式を選択してください。</p><div class="choice-grid export-levels">${Object.entries(labels).map(([id,label])=>`<button class="choice ${level===id?'selected':''}" data-level="${id}"><b>${label}</b></button>`).join('')}</div><p class="notice">選択中：${labels[level]}（${count}語）</p><label class="export-format">出力形式<select id="format"><option value="csv">CSVファイル</option><option value="pdf">PDFファイル</option></select></label><div class="stack">${btn('選択した形式で出力','btn btn-primary','id="output"')}</div></section>`);$('#back').onclick=home;document.querySelectorAll('[data-level]').forEach(x=>x.onclick=()=>{level=x.dataset.level;render();});$('#output').onclick=()=>{const rows=weakRows(level);if(!rows.length)return alert('出力できる苦手問題はありません。');$('#format').value==='csv'?exportWeakCsv(rows,labels[level]):printWeakPdf(rows,labels[level]);};};render(); }
  function exportWeakCsv(rows,label) { const esc=v=>'"'+String(v??'').replaceAll('"','""')+'"';const csv=['番号,カード種類,レベル,種別,英語,日本語,リトライ回数',...rows.map((x,i)=>[i+1,x.info.name,ln(x.q.level),x.q.type==='word'?'英単語':'英熟語',x.q.english,x.q.japanese,x.h.retryCount].map(esc).join(','))].join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`${label}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),0); }
  const pdfBytes = text => new TextEncoder().encode(text);
  const jpegBytes = dataUrl => { const raw=atob(dataUrl.split(',')[1]),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);return bytes; };
  function pdfPage(rows,label,page,total) { const canvas=document.createElement('canvas'),width=1240,height=1754,margin=70,header=56,rowHeight=42,columns=[48,105,72,72,210,405,88],ctx=canvas.getContext('2d');canvas.width=width;canvas.height=height;ctx.fillStyle='#fff';ctx.fillRect(0,0,width,height);ctx.fillStyle='#111';ctx.font='bold 30px "Yu Gothic", sans-serif';ctx.fillText(label,margin,65);ctx.font='20px "Yu Gothic", sans-serif';ctx.fillText(`出力日：${new Date().toLocaleDateString('ja-JP')}　${page} / ${total}ページ`,margin,100);const titles=['番号','カード種類','レベル','種別','英語','日本語','リトライ'],top=130;ctx.font='bold 18px "Yu Gothic", sans-serif';let x=margin;for(let i=0;i<columns.length;i++){ctx.fillStyle='#e2e8f0';ctx.fillRect(x,top,columns[i],header);ctx.fillStyle='#111';ctx.fillText(titles[i],x+6,top+34);x+=columns[i];}ctx.font='17px "Yu Gothic", sans-serif';rows.forEach((item,index)=>{const y=top+header+index*rowHeight,values=[String(item.index),item.info.name,ln(item.q.level),item.q.type==='word'?'英単語':'英熟語',item.q.english,item.q.japanese,`${item.h.retryCount}回`];x=margin;values.forEach((value,i)=>{const max=columns[i]-12;let text=value;while(ctx.measureText(text).width>max&&text.length>1)text=text.slice(0,-1);if(text!==value)text+='…';ctx.fillStyle='#111';ctx.fillText(text,x+6,y+27);x+=columns[i];});});ctx.strokeStyle='#111';ctx.lineWidth=1;const tableWidth=columns.reduce((a,b)=>a+b,0),bottom=top+header+rows.length*rowHeight;for(let y=top;y<=bottom;y+=rowHeight)ctx.strokeRect(margin,y,tableWidth,0);x=margin;columns.forEach(w=>{ctx.strokeRect(x,top,0,bottom-top);x+=w;});ctx.strokeRect(margin,top,tableWidth,bottom-top);return jpegBytes(canvas.toDataURL('image/jpeg',.94)); }
  function printWeakPdf(rows,label) { const perPage=36,pages=Array.from({length:Math.ceil(rows.length/perPage)},(_,i)=>pdfPage(rows.slice(i*perPage,(i+1)*perPage).map((row,index)=>({...row,index:i*perPage+index+1})),label,i+1,Math.ceil(rows.length/perPage))),objects=[null,null,null],pageRefs=[];let next=3;pages.forEach(image=>{const imageId=next++,contentId=next++,pageId=next++;objects[imageId]={image};objects[contentId]={text:'q\n595.28 0 0 841.89 0 0 cm\n/Im0 Do\nQ'};objects[pageId]={text:`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595.28 841.89] /Resources << /XObject << /Im0 ${imageId} 0 R >> /ProcSet [/PDF /ImageC] >> /Contents ${contentId} 0 R >>`};pageRefs.push(pageId);});objects[1]={text:'<< /Type /Catalog /Pages 2 0 R >>'};objects[2]={text:`<< /Type /Pages /Kids [${pageRefs.map(id=>`${id} 0 R`).join(' ')}] /Count ${pageRefs.length} >>`};const chunks=[pdfBytes('%PDF-1.3\n%âãÏÓ\n')],offsets=[0],size=chunks[0].length;for(let id=1;id<next;id++){offsets[id]=size;const item=objects[id],start=pdfBytes(`${id} 0 obj\n`);chunks.push(start);size+=start.length;if(item.image){const header=pdfBytes(`<< /Type /XObject /Subtype /Image /Width 1240 /Height 1754 /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${item.image.length} >>\nstream\n`),end=pdfBytes('\nendstream');chunks.push(header,item.image,end);size+=header.length+item.image.length+end.length;}else{const body=item.text.startsWith('q\n')?`<< /Length ${item.text.length} >>\nstream\n${item.text}\nendstream`:item.text,bytes=pdfBytes(body);chunks.push(bytes);size+=bytes.length;}const end=pdfBytes('\nendobj\n');chunks.push(end);size+=end.length;}const xref=size;let table=`xref\n0 ${next}\n0000000000 65535 f \n`;for(let id=1;id<next;id++)table+=`${String(offsets[id]).padStart(10,'0')} 00000 n \n`;const trailer=pdfBytes(`${table}trailer\n<< /Size ${next} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`);chunks.push(trailer);const url=URL.createObjectURL(new Blob(chunks,{type:'application/pdf'})),a=document.createElement('a');a.href=url;a.download=`${label}.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(url),0); }
  function printWeakPdf(rows,label) { try { const JsPDF=window.jspdf?.jsPDF;if(!JsPDF)throw new Error('PDF生成ライブラリを読み込めませんでした。');const doc=new JsPDF({orientation:'portrait',unit:'mm',format:'a4',compress:true}),perPage=36,total=Math.ceil(rows.length/perPage);for(let i=0;i<total;i++){if(i)doc.addPage();const image=pdfPage(rows.slice(i*perPage,(i+1)*perPage).map((row,index)=>({...row,index:i*perPage+index+1})),label,i+1,total);doc.addImage(image,'JPEG',0,0,210,297,undefined,'FAST');}doc.save(`${label}.pdf`); } catch(error) { console.error(error);alert(`PDFを生成できませんでした。${error.message}`); } }
  function directions(mode) { const heading = mode === 'study' ? 'カードの種類を選択' : mode === 'weak' ? '苦手問題の種類を選択' : '進捗を確認する種類を選択'; draw(`<section class="screen panel"><button class="back" id="back">← 戻る</button><h2>${heading}</h2><div class="choice-grid">${Object.entries(DIR).map(([d,x]) => `<button class="choice" data-d="${d}"><b>${x.name}</b><small>${x.flow}</small></button>`).join('')}</div></section>`); $('#back').onclick = home; document.querySelectorAll('[data-d]').forEach(x => x.onclick = () => mode === 'weak' ? weak(x.dataset.d) : levels(mode,x.dataset.d)); }
  function levels(mode,d) { draw(`<section class="screen panel"><button class="back" id="back">← 戻る</button><h2>レベルを選択</h2><p class="muted">${DIR[d].name}（${DIR[d].flow}）</p><div class="choice-grid"><button class="choice" data-l="junior"><b>中学</b><small>基礎的な単語・熟語</small></button><button class="choice" data-l="senior"><b>高校</b><small>入試・実用向けの語彙</small></button></div></section>`); $('#back').onclick = () => directions(mode); document.querySelectorAll('[data-l]').forEach(x => x.onclick = () => categories(mode,d,x.dataset.l)); }
  function categories(mode,d,l) { draw(`<section class="screen panel"><button class="back" id="back">← 戻る</button><h2>学習内容を選択</h2><p class="muted">${DIR[d].name}・${ln(l)}</p><div class="choice-grid">${['word','phrase','both'].map(c => `<button class="choice" data-c="${c}"><b>${cn(c)}</b><small>${qs(l,c).length}語</small></button>`).join('')}</div></section>`); $('#back').onclick = () => levels(mode,d); document.querySelectorAll('[data-c]').forEach(x => x.onclick = () => mode === 'study' ? start(d,l,x.dataset.c) : prog(d,l,x.dataset.c)); }
  function start(d,l,c) { const p = progress(d,l,c), sc = scope(d), has = !!sc.sessions[sessionKey(l,c)]; draw(`<section class="screen panel"><button class="back" id="back">← 戻る</button><h2>学習を開始</h2><p class="muted">${DIR[d].name}・${ln(l)}・${cn(c)}</p><div class="notice">現在の学習状況：${p.studied} / ${p.total}語（${p.pct}%）</div><div class="stack">${btn('最初から','btn btn-primary','id="fresh"')}${btn('前回の続きから','btn',`id="resume" ${has ? '' : 'disabled'}`)}</div></section>`); $('#back').onclick = () => categories('study',d,l); $('#fresh').onclick = () => confirm('この種類・レベルの学習履歴をリセットして最初から開始しますか？','最初から開始',() => { const ids = new Set(qs(l,c).map(q => q.id)); ids.forEach(id => delete sc.histories[id]); sc.reviewQueue = sc.reviewQueue.filter(x => !ids.has(x.questionId)); sc.sessions[sessionKey(l,c)] = makeSession(l,c); save(); open(d,l,c); }); $('#resume').onclick = () => open(d,l,c); }
  function open(d,l,c) { active = {d,l,c,answer:false}; const sc = scope(d); sc.sessions[sessionKey(l,c)] ??= makeSession(l,c); next(); }
  function pick(s,d) { const sc = scope(d), all = qs(s.level,s.category), newCards = all.filter(q => !sc.histories[q.id]?.firstStudied), inScope = sc.reviewQueue.filter(x => all.some(q => q.id === x.questionId)); const sort = a => a.sort((x,y) => y.retryCount-x.retryCount || x.remainingQuestions-y.remainingQuestions || new Date(x.lastShownAt)-new Date(y.lastShownAt)); const ready = sort(inScope.filter(x => x.remainingQuestions <= 0)); if (!newCards.length) { s.studyMode='review'; const r = ready[0] || sort(inScope)[0]; return r ? {id:r.questionId,type:'review'} : null; } s.studyMode='normal'; return s.consecutiveReviewCount < 3 && ready[0] ? {id:ready[0].questionId,type:'review'} : {id:newCards[0].id,type:'new'}; }
  function next() { const sc = scope(active.d), s = sc.sessions[sessionKey(active.l,active.c)], n = pick(s,active.d); if (!n) return result(true); const h = sc.histories[n.id] || {questionId:n.id,displayCount:0,retryCount:0,learned:false,firstStudied:false}; h.firstStudied=true; h.displayCount++; h.lastStudiedAt=new Date().toISOString(); sc.histories[n.id]=h; s.current=n; s.consecutiveReviewCount=n.type==='review' ? s.consecutiveReviewCount+1 : 0; active.card={q:qid(n.id),h,n}; active.answer=false; save(); card(); }
  function answerHtml(q,d) { return d === 'jaEn' ? `<div class="answer"><p><strong>英語</strong><br><b class="answer-main">${q.english}</b></p><p><strong>例文</strong><br>${q.example}</p><p><strong>例文の意味</strong><br>${q.exampleJapanese}</p></div>` : `<div class="answer"><p><strong>日本語</strong><br><b class="answer-main">${q.japanese}</b></p><p><strong>例文</strong><br>${q.example}</p><p><strong>日本語訳</strong><br>${q.exampleJapanese}</p></div>`; }
  function card() { const {q,h,n}=active.card, s=scope(active.d).sessions[sessionKey(active.l,active.c)], p=progress(active.d,active.l,active.c), prompt=active.d==='jaEn'?q.japanese:q.english, label=s.studyMode==='review'?'復習中':n.type==='review'?'復習カード':'新しいカード', bc=s.studyMode==='review'?'total':n.type==='review'?'review':''; draw(`<section class="screen"><div class="card"><div class="card-top"><span>${DIR[active.d].name}・${p.studied} / ${p.total}語</span><span class="badge ${bc}">${label}</span></div><div class="progress-track"><div class="progress-value" style="width:${p.pct}%"></div></div><div class="muted">学習済み ${p.pct}%</div><div class="counts"><span>このカードの表示 ${h.displayCount}回</span><span>リトライ ${h.retryCount}回</span></div><div class="word-with-sound"><h1 class="word">${prompt}</h1><button class="sound-button" id="sound" type="button" aria-label="英語を再生">🔊</button></div>${active.answer ? `${answerHtml(q,active.d)}<div class="card-actions two-actions">${btn('リトライ','btn btn-retry','id="retry"')}${btn('覚えた','btn btn-success','id="learn"')}</div>` : `<div class="card-actions">${btn('答えを見る','btn btn-primary','id="answer"')}</div>`}<div class="exit-action">${btn('中断','btn btn-outline','id="exit"')}</div></div></section>`); if (!active.answer) $('#answer').onclick=()=>{active.answer=true;card();}; else { $('#retry').onclick=()=>grade('retry'); $('#learn').onclick=()=>grade('learned'); } $('#sound').onclick=()=>speak(q.english); $('#exit').onclick=()=>confirm('学習を中断しますか？進捗は保存され、次回「前回の続きから」再開できます。','中断する',()=>{save();home();}); }
  function grade(action) { const sc=scope(active.d), s=sc.sessions[sessionKey(active.l,active.c)], {h,n}=active.card; s.sessionStats.cards++; n.type==='new'?s.sessionStats.newCards++:s.sessionStats.reviewCards++; if (action==='retry') { h.retryCount++; const interval=state.settings.reviewIntervals[h.retryCount>=5?'5plus':String(h.retryCount)]; sc.reviewQueue=sc.reviewQueue.filter(x=>x.questionId!==h.questionId); sc.reviewQueue.push({questionId:h.questionId,retryCount:h.retryCount,interval,remainingQuestions:interval,lastShownAt:new Date().toISOString()}); } else { h.learned=true; sc.reviewQueue=sc.reviewQueue.filter(x=>x.questionId!==h.questionId); h.displayCount===1?s.sessionStats.learnedFirstTry++:h.displayCount===2?s.sessionStats.learnedTwoTries++:s.sessionStats.learnedThreePlus++; } sc.reviewQueue=sc.reviewQueue.map(x=>x.questionId===h.questionId?x:{...x,remainingQuestions:x.remainingQuestions-1}); save(); s.sessionStats.cards%50===0?result(false):next(); }
  const retries = (d,l,c) => qs(l,c).map(q=>({q,h:scope(d).histories[q.id]||{retryCount:0}})).filter(x=>x.h.retryCount>0).sort((a,b)=>b.h.retryCount-a.h.retryCount||a.q.english.localeCompare(b.q.english));
  function exportCsv(d,l,c) { const esc=v=>'"'+String(v??'').replaceAll('"','""')+'"', rows=retries(d,l,c); const csv=['番号,カード種類,レベル,種別,英語,日本語,リトライ回数',...rows.map((x,i)=>[i+1,DIR[d].name,ln(x.q.level),x.q.type==='word'?'英単語':'英熟語',x.q.english,x.q.japanese,x.h.retryCount].map(esc).join(','))].join('\r\n'); const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`苦手問題_${DIR[d].name}_${ln(l)}_${cn(c)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),0); }
  function result(done) { const sc=scope(active.d),s=sc.sessions[sessionKey(active.l,active.c)],x=s.sessionStats,pending=sc.reviewQueue.filter(x=>qs(active.l,active.c).some(q=>q.id===x.questionId)).length,list=retries(active.d,active.l,active.c); draw(`<section class="screen panel"><h2>${done?'学習完了':'今回の学習結果'}</h2><p class="lead">${DIR[active.d].name}・${done?'おつかれさまでした。':'50カードを学習しました。'}</p><div class="stat-grid"><div class="stat">学習したカード<b>${x.cards}回</b></div><div class="stat">新規学習<b>${x.newCards}語</b></div><div class="stat">復習<b>${x.reviewCards}語</b></div><div class="stat">復習待ち<b>${pending}語</b></div><div class="stat">1回で覚えた<b>${x.learnedFirstTry}語</b></div><div class="stat">2回で覚えた<b>${x.learnedTwoTries}語</b></div><div class="stat">3回以上<b>${x.learnedThreePlus}語</b></div></div><h3>リトライしたカード</h3>${list.length?`<ol class="list">${list.map(({q,h})=>`<li><span>${active.d==='jaEn'?q.japanese:q.english}<small class="muted">　${active.d==='jaEn'?q.english:q.japanese}</small></span><b>リトライ：${h.retryCount}回</b></li>`).join('')}</ol>${btn('CSVファイルを保存','btn btn-outline','id="csv"')}`:'<p class="empty">今回の学習に「リトライ」したカードはありません。</p>'}<div class="stack">${!done?btn('学習を続ける','btn btn-primary','id="go"'):''}${btn('苦手問題を復習','btn btn-retry','id="weak"')}${btn('トップへ戻る','btn btn-outline','id="home"')}</div></section>`); $('#go')?.addEventListener('click',next); $('#csv')?.addEventListener('click',()=>exportCsv(active.d,active.l,active.c)); $('#weak').onclick=()=>directions('weak'); $('#home').onclick=home; }
  function prog(d,l,c) { const sc=scope(d),p=progress(d,l,c),all=qs(l,c).map(q=>({q,h:sc.histories[q.id]||{retryCount:0}})),count=n=>all.filter(x=>x.h.retryCount===n).length,list=all.filter(x=>x.h.retryCount>0).sort((a,b)=>b.h.retryCount-a.h.retryCount).slice(0,5),waiting=sc.reviewQueue.filter(x=>qs(l,c).some(q=>q.id===x.questionId)).length; draw(`<section class="screen panel"><button class="back" id="back">← 戻る</button><h2>${DIR[d].name}・${ln(l)}${cn(c)}</h2><div class="progress-track"><div class="progress-value" style="width:${p.pct}%"></div></div><p><b>${p.studied} / ${p.total}</b>語（${p.pct}%）</p><div class="stat-grid"><div class="stat">未学習<b>${p.unstudied}語</b></div><div class="stat">復習待ち<b>${waiting}語</b></div>${[1,2,3,4].map(n=>`<div class="stat">${n}回間違い<b>${count(n)}語</b></div>`).join('')}<div class="stat">5回以上<b>${all.filter(x=>x.h.retryCount>=5).length}語</b></div></div><h3>苦手なカード</h3>${list.length?`<ol class="list">${list.map(x=>`<li><span>${d==='jaEn'?x.q.japanese:x.q.english}</span><b>リトライ：${x.h.retryCount}回</b></li>`).join('')}</ol>`:'<p class="empty">まだ苦手問題はありません。</p>'}</section>`); $('#back').onclick=()=>categories('prog',d,l); }
  function weak(d) { const sc=scope(d), ids=Object.values(sc.histories).filter(h=>h.retryCount && qid(h.questionId)).sort((a,b)=>b.retryCount-a.retryCount).map(h=>h.questionId); active={d,weak:{ids,i:0,shown:null},answer:false}; if(!ids.length) { draw(`<section class="screen panel empty"><h2>苦手問題はありません</h2><p>${DIR[d].name}で「リトライ」を押したカードがここに表示されます。</p>${btn('トップへ戻る','btn btn-primary','id="home"')}</section>`); $('#home').onclick=home; return; } weakCard(); }
  function weakCard() { const w=active.weak;if(w.i>=w.ids.length){draw(`<section class="screen panel"><h2>苦手問題の復習完了</h2>${btn('トップへ戻る','btn btn-primary','id="home"')}</section>`);$('#home').onclick=home;return;} const q=qid(w.ids[w.i]),h=scope(active.d).histories[q.id];if(w.shown!==q.id){h.displayCount++;w.shown=q.id;save();} const prompt=active.d==='jaEn'?q.japanese:q.english; draw(`<section class="screen"><div class="card"><div class="card-top"><span>${DIR[active.d].name}・${w.i+1} / ${w.ids.length}語</span><span class="badge review">苦手問題復習</span></div><div class="counts"><span>このカードの表示 ${h.displayCount}回</span><span>リトライ ${h.retryCount}回</span></div><div class="word-with-sound"><h1 class="word">${prompt}</h1><button class="sound-button" id="sound" type="button" aria-label="英語を再生">🔊</button></div>${active.answer?`${answerHtml(q,active.d)}<div class="card-actions two-actions">${btn('リトライ','btn btn-retry','id="retry"')}${btn('覚えた','btn btn-success','id="learn"')}</div>`:`<div class="card-actions">${btn('答えを見る','btn btn-primary','id="answer"')}</div>`}<div class="exit-action">${btn('中断','btn btn-outline','id="exit"')}</div></div></section>`); if(!active.answer)$('#answer').onclick=()=>{active.answer=true;weakCard();};else{$('#retry').onclick=()=>weakGrade('retry');$('#learn').onclick=()=>weakGrade('learn');}$('#sound').onclick=()=>speak(q.english);$('#exit').onclick=()=>confirm('苦手問題の復習を中断しますか？進捗は保存されます。','中断する',()=>{save();home();}); }
  function weakGrade(action) { const sc=scope(active.d),w=active.weak,h=sc.histories[w.ids[w.i]];if(action==='retry'){h.retryCount++;const interval=state.settings.reviewIntervals[h.retryCount>=5?'5plus':String(h.retryCount)];sc.reviewQueue=sc.reviewQueue.filter(x=>x.questionId!==h.questionId);sc.reviewQueue.push({questionId:h.questionId,retryCount:h.retryCount,interval,remainingQuestions:interval,lastShownAt:new Date().toISOString()});}else{h.learned=true;sc.reviewQueue=sc.reviewQueue.filter(x=>x.questionId!==h.questionId);}sc.reviewQueue=sc.reviewQueue.map(x=>x.questionId===h.questionId?x:{...x,remainingQuestions:x.remainingQuestions-1});save();w.i++;w.shown=null;active.answer=false;weakCard(); }
  function settings() { const v=state.settings.reviewIntervals, rows=[['1','1回間違い'],['2','2回間違い'],['3','3回間違い'],['4','4回間違い'],['5plus','5回以上間違い']].map(([k,t])=>`<label class="form-row"><span>${t}<small class="muted">（問後）</small></span><input type="number" min="1" max="100" data-k="${k}" value="${v[k]}"></label>`).join('');draw(`<section class="screen panel"><button class="back" id="back">← 戻る</button><h2>設定</h2><h3>復習間隔設定</h3><p class="muted">1〜100の整数で設定できます。変更後に「リトライ」を押したカードから適用されます。</p>${rows}<div class="stack">${btn('設定を保存','btn btn-primary','id="save"')}${btn('復習間隔を初期値に戻す','btn btn-outline','id="def"')}${btn('学習履歴をリセット','btn btn-danger','id="clear"')}</div></section>`);$('#back').onclick=home;$('#save').onclick=()=>{const o={};document.querySelectorAll('[data-k]').forEach(x=>o[x.dataset.k]=Number(x.value));if(Object.values(o).some(x=>!Number.isInteger(x)||x<1||x>100))return alert('各項目に1〜100の整数を入力してください。');state.settings.reviewIntervals=o;save();alert('設定を保存しました。');};$('#def').onclick=()=>confirm('復習間隔を初期値に戻しますか？','初期値に戻す',()=>{state.settings.reviewIntervals={...DEF};save();settings();});$('#clear').onclick=()=>confirm('英和・和英の学習履歴、復習キュー、途中セッション、設定をすべてリセットしますか？','すべてリセット',()=>{localStorage.removeItem(KEY);state=init();home();}); }
  function confirm(message,label,ok) { document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="modal"><div class="modal-box"><h3>確認</h3><p>${message}</p><div class="modal-actions">${btn('キャンセル','btn btn-outline','id="cancel"')}${btn(label,'btn btn-danger','id="yes"')}</div></div></div>`);$('#cancel').onclick=()=>$('#modal').remove();$('#yes').onclick=()=>{$('#modal').remove();ok();}; }
  home();
})();
