/* Standalone browser script: no imports, bundler, or local web server required. */
(() => {
  const raw = [
    ['j1','junior','word','apple','りんご','I ate an apple.','私はりんごを食べました。'],['j2','junior','word','important','重要な、大切な','This is an important question.','これは重要な質問です。'],['j3','junior','word','beautiful','美しい','The flower is beautiful.','その花は美しいです。'],['j4','junior','word','environment','環境','We should protect the environment.','私たちは環境を守るべきです。'],['j5','junior','word','different','異なる','My idea is different from yours.','私の考えはあなたの考えと異なります。'],['j6','junior','word','practice','練習する','I practice English every day.','私は毎日英語を練習します。'],['j7','junior','word','usually','たいてい','I usually walk to school.','私はたいてい歩いて学校へ行きます。'],['j8','junior','word','promise','約束','I made a promise.','私は約束をしました。'],['j9','junior','word','history','歴史','We studied history.','私たちは歴史を学びました。'],['j10','junior','word','language','言語','English is a useful language.','英語は役に立つ言語です。'],['j11','junior','word','prepare','準備する','Please prepare for the test.','テストの準備をしてください。'],['j12','junior','word','explain','説明する','Can you explain this word?','この単語を説明できますか。'],['j13','junior','word','receive','受け取る','I received a letter.','私は手紙を受け取りました。'],['j14','junior','word','especially','特に','I especially like this song.','私は特にこの歌が好きです。'],['j15','junior','word','choose','選ぶ','Choose the best answer.','最も良い答えを選びなさい。'],['j16','junior','word','future','将来','Nobody knows the future.','誰も将来を知りません。'],['j17','junior','word','country','国','Japan is a beautiful country.','日本は美しい国です。'],['j18','junior','word','member','メンバー','She is a club member.','彼女はクラブのメンバーです。'],['j19','junior','word','necessary','必要な','Sleep is necessary.','睡眠は必要です。'],['j20','junior','word','continue','続ける','Please continue your work.','作業を続けてください。'],
    ['jp1','junior','phrase','look for','～を探す','I am looking for my key.','私は鍵を探しています。'],['jp2','junior','phrase','be interested in','～に興味がある','I am interested in science.','私は科学に興味があります。'],['jp3','junior','phrase','take care of','～の世話をする','She takes care of her dog.','彼女は犬の世話をします。'],['jp4','junior','phrase','be good at','～が得意','He is good at tennis.','彼はテニスが得意です。'],['jp5','junior','phrase','for example','たとえば','For example, apples are fruit.','たとえば、りんごは果物です。'],['jp6','junior','phrase','have to','～しなければならない','I have to go home.','私は帰宅しなければなりません。'],
    ['s1','senior','word','available','利用できる','The information is available online.','その情報はオンラインで利用できます。'],['s2','senior','word','increase','増加する','The number increased last year.','その数は昨年増えました。'],['s3','senior','word','benefit','利益、恩恵','Exercise has many benefits.','運動には多くの利点があります。'],['s4','senior','word','require','必要とする','This job requires experience.','この仕事には経験が必要です。'],['s5','senior','word','evidence','証拠','There is no evidence of damage.','損害の証拠はありません。'],['s6','senior','word','consider','考慮する','Please consider my suggestion.','私の提案を検討してください。'],['s7','senior','word','opportunity','機会','This is a great opportunity.','これは素晴らしい機会です。'],['s8','senior','word','prevent','防ぐ','Washing hands prevents illness.','手洗いは病気を防ぎます。'],
    ['sp1','senior','phrase','as a result','結果として','As a result, we succeeded.','結果として、私たちは成功しました。'],['sp2','senior','phrase','in addition to','～に加えて','In addition to English, she studies French.','英語に加えて、彼女はフランス語を学びます。'],['sp3','senior','phrase','be responsible for','～に責任がある','He is responsible for this project.','彼はこの計画に責任があります。'],['sp4','senior','phrase','deal with','～に対処する','We must deal with the problem.','私たちは問題に対処しなければなりません。'],['sp5','senior','phrase','take advantage of','～を利用する','Take advantage of this chance.','この機会を利用しなさい。'],['sp6','senior','phrase','in spite of','～にもかかわらず','In spite of the rain, we played.','雨にもかかわらず、私たちはプレーしました。']
  ];
  const existingCards=raw.map(([id,level,type,english,japanese,example,exampleJapanese])=>({id,level,type,english,japanese,example,exampleJapanese,partOfSpeech:'other',curriculumLevel:level==='junior'?'junior_high':'high_school',grade:level==='junior'?1:1,category:type==='phrase'?'phrase':'basic',priority:1,pronunciation:english,tags:[level==='junior'?'中学':'高校',type==='phrase'?'熟語':'既存'],enabled:true}));
  const existingEnglish=new Set(existingCards.map(q=>`${q.type}:${q.english.toLowerCase()}`));
  const Q=[...existingCards,...(window.EnglishCardCatalog||[]).filter(q=>!existingEnglish.has(`${q.type}:${q.english.toLowerCase()}`))];
  const $=s=>document.querySelector(s), app=$('#app'), KEY='englishCardApp_v1', DEF={'1':10,'2':7,'3':5,'4':3,'5plus':2};
  let state, active={};
  const init=()=>({version:1,settings:{reviewIntervals:{...DEF}},histories:{},reviewQueue:[],sessions:{}});
  try { state={...init(),...JSON.parse(localStorage.getItem(KEY)||'null')}; state.settings={reviewIntervals:{...DEF,...(state.settings?.reviewIntervals||{})}}; } catch { state=init(); }
  const save=()=>localStorage.setItem(KEY,JSON.stringify(state)), qs=(l,c='both')=>Q.filter(q=>q.level===l&&(c==='both'||q.type===c)), qid=id=>Q.find(q=>q.id===id), key=(l,c)=>l+':'+c, ln=l=>l==='junior'?'中学':'高校', cn=c=>({word:'英単語',phrase:'英熟語',both:'英単語＋英熟語'})[c];
  const btn=(t,cl='btn',a='')=>`<button class="${cl}" ${a}>${t}</button>`, draw=h=>app.innerHTML=h, session=(l,c)=>({level:l,category:c,consecutiveReviewCount:0,studyMode:'normal',current:null,sessionStats:{cards:0,newCards:0,reviewCards:0,learnedFirstTry:0,learnedTwoTries:0,learnedThreePlus:0},startedAt:new Date().toISOString()});
  const speak=(text)=>{if(!('speechSynthesis' in window)){alert('このブラウザは音声再生に対応していません。');return}window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.85;window.speechSynthesis.speak(u)};
  const progress=(l,c)=>{const a=qs(l,c),n=a.filter(q=>state.histories[q.id]?.firstStudied).length;return{total:a.length,studied:n,unstudied:a.length-n,pct:a.length?Math.round(n/a.length*100):0}};
  function home(){active={};draw(`<section class="screen panel home-panel"><button class="settings-button" id="set" type="button" aria-label="設定">⚙</button><h1>英単語・英熟語カード</h1><p class="lead">くり返し学習で、英語を自分のものに。</p><div class="stack">${btn('学習を始める','btn btn-primary','id="start"')}${btn('苦手問題を復習','btn btn-retry','id="weak"')}${btn('学習進捗を見る','btn','id="prog"')}</div></section>`);$('#start').onclick=()=>levels('study');$('#prog').onclick=()=>levels('prog');$('#weak').onclick=weak;$('#set').onclick=settings}
  function levels(mode){draw(`<section class="screen panel"><button class="back" id="back">← 戻る</button><h2>レベルを選択</h2><div class="choice-grid"><button class="choice" data-l="junior"><b>中学</b><small>基礎的な単語・熟語</small></button><button class="choice" data-l="senior"><b>高校</b><small>標準〜受験向けの語彙</small></button></div></section>`);$('#back').onclick=home;document.querySelectorAll('[data-l]').forEach(x=>x.onclick=()=>categories(mode,x.dataset.l))}
  function categories(mode,l){draw(`<section class="screen panel"><button class="back" id="back">← 戻る</button><h2>学習内容を選択</h2><p class="muted">${ln(l)}の学習内容を選んでください。</p><div class="choice-grid">${['word','phrase','both'].map(c=>`<button class="choice" data-c="${c}"><b>${cn(c)}</b><small>${qs(l,c).length}問</small></button>`).join('')}</div></section>`);$('#back').onclick=()=>levels(mode);document.querySelectorAll('[data-c]').forEach(x=>x.onclick=()=>mode==='study'?start(l,x.dataset.c):prog(l,x.dataset.c))}
  function start(l,c){const p=progress(l,c), has=!!state.sessions[key(l,c)];draw(`<section class="screen panel"><button class="back" id="back">← 戻る</button><h2>学習方法を選択</h2><p class="muted">${ln(l)}・${cn(c)}</p><div class="notice">前回の進捗：${p.studied} / ${p.total}問（${p.pct}%）</div><div class="stack">${btn('最初から','btn btn-primary','id="fresh"')}${btn('前回の続きから','btn',`id="resume" ${has?'':'disabled'}`)}</div></section>`);$('#back').onclick=()=>categories('study',l);$('#fresh').onclick=()=>confirm('学習進捗をリセットして最初から開始しますか？','最初から開始',()=>{const ids=new Set(qs(l,c).map(q=>q.id));ids.forEach(id=>delete state.histories[id]);state.reviewQueue=state.reviewQueue.filter(x=>!ids.has(x.questionId));state.sessions[key(l,c)]=session(l,c);save();open(l,c)});$('#resume').onclick=()=>open(l,c)}
  function open(l,c){active={l,c,answer:false};state.sessions[key(l,c)]??=session(l,c);next()}
  function pick(s){const all=qs(s.level,s.category),newQ=all.filter(q=>!state.histories[q.id]?.firstStudied), inScope=state.reviewQueue.filter(x=>all.some(q=>q.id===x.questionId)), sort=a=>a.sort((x,y)=>y.retryCount-x.retryCount||x.remainingQuestions-y.remainingQuestions||new Date(x.lastShownAt)-new Date(y.lastShownAt)), ready=sort(inScope.filter(x=>x.remainingQuestions<=0));if(!newQ.length){s.studyMode='review';const r=ready[0]||sort(inScope)[0];return r?{id:r.questionId,type:'review'}:null} s.studyMode='normal';if(s.consecutiveReviewCount<3&&ready[0])return{id:ready[0].questionId,type:'review'};return{id:newQ[0].id,type:'new'}}
  function next(){const s=state.sessions[key(active.l,active.c)], n=pick(s);if(!n)return result(true);const h=state.histories[n.id]||{questionId:n.id,displayCount:0,retryCount:0,learned:false,firstStudied:false};h.firstStudied=true;h.displayCount++;h.lastStudiedAt=new Date().toISOString();state.histories[n.id]=h;s.current=n;s.consecutiveReviewCount=n.type==='review'?s.consecutiveReviewCount+1:0;active.card={q:qid(n.id),h,n};active.answer=false;save();card()}
  function card(){const {q,h,n}=active.card,s=state.sessions[key(active.l,active.c)],p=progress(active.l,active.c),label=s.studyMode==='review'?'総復習':n.type==='review'?'復習問題':'新しい問題',bc=s.studyMode==='review'?'total':n.type==='review'?'review':'';draw(`<section class="screen"><div class="card"><div class="card-top"><span>${p.studied} / ${p.total}問</span><span class="badge ${bc}">${label}</span></div><div class="progress-track"><div class="progress-value" style="width:${p.pct}%"></div></div><div class="muted">新規進捗 ${p.pct}%</div><div class="counts"><span>今回の挑戦：${h.displayCount}回目</span><span>リトライ：${h.retryCount}回</span></div><div class="word-with-sound"><h1 class="word">${q.english}</h1><button class="sound-button" id="sound" type="button" aria-label="${q.english}を再生">🔊</button></div>${active.answer?`<div class="answer"><p><strong>意味：</strong><br>${q.japanese}</p><p><strong>例文：</strong><br>${q.example}</p><p><strong>日本語：</strong><br>${q.exampleJapanese}</p></div><div class="card-actions two-actions">${btn('リトライ','btn btn-retry','id="retry"')}${btn('覚えた','btn btn-success','id="learn"')}</div>`:`<div class="card-actions">${btn('答えを見る','btn btn-primary','id="answer"')}</div>`}<div class="exit-action">${btn('終了','btn btn-outline','id="exit"')}</div></div></section>`);if(!active.answer)$('#answer').onclick=()=>{active.answer=true;card()};else{$('#retry').onclick=()=>answer('retry');$('#learn').onclick=()=>answer('learned')};$('#sound').onclick=()=>speak(q.english);$('#exit').onclick=()=>confirm('学習を終了しますか？ 進捗は保存され、次回「前回の続きから」で再開できます。','終了する',()=>{save();home()})}
  function answer(act){const s=state.sessions[key(active.l,active.c)],{h,n}=active.card;s.sessionStats.cards++;n.type==='new'?s.sessionStats.newCards++:s.sessionStats.reviewCards++;if(act==='retry'){h.retryCount++;const i=state.settings.reviewIntervals[h.retryCount>=5?'5plus':String(h.retryCount)];state.reviewQueue=state.reviewQueue.filter(x=>x.questionId!==h.questionId);state.reviewQueue.push({questionId:h.questionId,retryCount:h.retryCount,interval:i,remainingQuestions:i,lastShownAt:new Date().toISOString()})}else{h.learned=true;state.reviewQueue=state.reviewQueue.filter(x=>x.questionId!==h.questionId);h.displayCount===1?s.sessionStats.learnedFirstTry++:h.displayCount===2?s.sessionStats.learnedTwoTries++:s.sessionStats.learnedThreePlus++}state.reviewQueue=state.reviewQueue.map(x=>x.questionId===h.questionId?x:{...x,remainingQuestions:x.remainingQuestions-1});save();s.sessionStats.cards%50===0?result(false):next()}
  const retryList=(l,c)=>qs(l,c).map(q=>({q,h:state.histories[q.id]||{retryCount:0}})).filter(x=>x.h.retryCount>0).sort((a,b)=>b.h.retryCount-a.h.retryCount||a.q.english.localeCompare(b.q.english));
  function exportCsv(l,c){const rows=retryList(l,c),esc=v=>'"'+String(v??'').replaceAll('"','""')+'"';const csv=['順位,レベル,種類,英語,日本語,リトライ回数',...rows.map((x,i)=>[i+1,ln(x.q.level),x.q.type==='word'?'英単語':'英熟語',x.q.english,x.q.japanese,x.h.retryCount].map(esc).join(','))].join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`苦手問題_${ln(l)}_${cn(c)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),0)}
  function result(done){const s=state.sessions[key(active.l,active.c)],x=s.sessionStats,pending=state.reviewQueue.filter(x=>qs(active.l,active.c).some(q=>q.id===x.questionId)).length,retries=retryList(active.l,active.c);draw(`<section class="screen panel"><h2>${done?'学習完了':'今回の学習結果'}</h2><p class="lead">${done?'おつかれさまでした。復習キューは空です。':'50カードを学習しました。'}</p><div class="stat-grid"><div class="stat">学習したカード<b>${x.cards}回</b></div><div class="stat">新規学習<b>${x.newCards}問</b></div><div class="stat">復習<b>${x.reviewCards}問</b></div><div class="stat">復習待ち<b>${pending}問</b></div><div class="stat">1回で覚えた<b>${x.learnedFirstTry}問</b></div><div class="stat">2回で覚えた<b>${x.learnedTwoTries}問</b></div><div class="stat">3回以上<b>${x.learnedThreePlus}問</b></div></div><h3>リトライした問題</h3>${retries.length?`<ol class="list">${retries.map(({q,h})=>`<li><span>${q.english}<small class="muted">　${q.japanese}</small></span><b>リトライ：${h.retryCount}回</b></li>`).join('')}</ol>${btn('CSVファイルを出力','btn btn-outline','id="csv"')}`:'<p class="empty">今回の範囲に「リトライ」の問題はありません。</p>'}<div class="stack">${!done?btn('学習を続ける','btn btn-primary','id="go"'):''}${btn('苦手問題を復習','btn btn-retry','id="weak"')}${btn('トップへ戻る','btn btn-outline','id="home"')}</div></section>`);$('#go')?.addEventListener('click',next);$('#csv')?.addEventListener('click',()=>exportCsv(active.l,active.c));$('#weak').onclick=weak;$('#home').onclick=home}
  function prog(l,c){const p=progress(l,c),a=qs(l,c).map(q=>({q,h:state.histories[q.id]||{retryCount:0}})),b=n=>a.filter(x=>x.h.retryCount===n).length,r=a.filter(x=>x.h.retryCount>0).sort((x,y)=>y.h.retryCount-x.h.retryCount).slice(0,5),waiting=state.reviewQueue.filter(x=>qs(l,c).some(q=>q.id===x.questionId)).length;draw(`<section class="screen panel"><button class="back" id="back">← 戻る</button><h2>${ln(l)}${cn(c)}</h2><div class="progress-track"><div class="progress-value" style="width:${p.pct}%"></div></div><p><b>${p.studied} / ${p.total}</b>問（${p.pct}%）</p><div class="stat-grid"><div class="stat">未学習<b>${p.unstudied}問</b></div><div class="stat">復習待ち<b>${waiting}問</b></div>${[1,2,3,4].map(n=>`<div class="stat">${n}回間違い<b>${b(n)}問</b></div>`).join('')}<div class="stat">5回以上<b>${a.filter(x=>x.h.retryCount>=5).length}問</b></div></div><h3>苦手な単語・熟語</h3>${r.length?`<ol class="list">${r.map(x=>`<li><span>${x.q.english}</span><b>リトライ：${x.h.retryCount}回</b></li>`).join('')}</ol>`:'<p class="empty">まだ苦手問題はありません。</p>'}</section>`);$('#back').onclick=()=>categories('prog',l)}
  function weak(){const ids=Object.values(state.histories).filter(h=>h.retryCount).sort((a,b)=>b.retryCount-a.retryCount).map(h=>h.questionId);active={direction,weak:{ids,i:0,shown:null},answer:false};if(!ids.length){draw(`<section class="screen panel empty"><h2>苦手問題はありません</h2><p>「リトライ」を押したカードがここに表示されます。</p>${btn('トップへ戻る','btn btn-primary','id="home"')}</section>`);$('#home').onclick=home;return}weakCard()}
  function weakCard(){const w=active.weak;if(w.i>=w.ids.length){draw(`<section class="screen panel"><h2>苦手問題の復習完了</h2>${btn('トップへ戻る','btn btn-primary','id="home"')}</section>`);$('#home').onclick=home;return}const q=qid(w.ids[w.i]),h=state.histories[q.id];if(w.shown!==q.id){h.displayCount++;w.shown=q.id;save()}draw(`<section class="screen"><div class="card"><div class="card-top"><span>${w.i+1} / ${w.ids.length}問</span><span class="badge review">苦手問題復習</span></div><div class="counts"><span>今回の挑戦：${h.displayCount}回目</span><span>リトライ：${h.retryCount}回</span></div><div class="word-with-sound"><h1 class="word">${q.english}</h1><button class="sound-button" id="sound" type="button" aria-label="${q.english}を再生">🔊</button></div>${active.answer?`<div class="answer"><p><strong>意味：</strong><br>${q.japanese}</p><p><strong>例文：</strong><br>${q.example}</p><p><strong>日本語：</strong><br>${q.exampleJapanese}</p></div><div class="card-actions two-actions">${btn('リトライ','btn btn-retry','id="retry"')}${btn('覚えた','btn btn-success','id="learn"')}</div>`:`<div class="card-actions">${btn('答えを見る','btn btn-primary','id="answer"')}</div>`}</div></section>`);if(!active.answer)$('#answer').onclick=()=>{active.answer=true;weakCard()};else{$('#retry').onclick=()=>weakAnswer('retry');$('#learn').onclick=()=>weakAnswer('learned')};$('#sound').onclick=()=>speak(q.english)}
  function weakAnswer(a){const w=active.weak,h=state.histories[w.ids[w.i]];if(a==='retry'){h.retryCount++;const i=state.settings.reviewIntervals[h.retryCount>=5?'5plus':String(h.retryCount)];state.reviewQueue=state.reviewQueue.filter(x=>x.questionId!==h.questionId);state.reviewQueue.push({questionId:h.questionId,retryCount:h.retryCount,interval:i,remainingQuestions:i,lastShownAt:new Date().toISOString()})}else{h.learned=true;state.reviewQueue=state.reviewQueue.filter(x=>x.questionId!==h.questionId)}state.reviewQueue=state.reviewQueue.map(x=>x.questionId===h.questionId?x:{...x,remainingQuestions:x.remainingQuestions-1});save();w.i++;w.shown=null;active.answer=false;weakCard()}
  function settings(){let v=state.settings.reviewIntervals,rows=[['1','1回間違い'],['2','2回間違い'],['3','3回間違い'],['4','4回間違い'],['5plus','5回以上間違い']].map(([k,t])=>`<label class="form-row"><span>${t}<small class="muted">（問後）</small></span><input type="number" min="1" max="100" data-k="${k}" value="${v[k]}"></label>`).join('');draw(`<section class="screen panel"><button class="back" id="back">← 戻る</button><h2>設定</h2><h3>復習間隔設定</h3><p class="muted">1〜100の整数で設定できます。変更後に「リトライ」を押したカードから適用されます。</p>${rows}<div class="stack">${btn('設定を保存','btn btn-primary','id="save"')}${btn('復習間隔を初期値に戻す','btn btn-outline','id="def"')}${btn('学習履歴をリセット','btn btn-danger','id="clear"')}</div></section>`);$('#back').onclick=home;$('#save').onclick=()=>{const o={};document.querySelectorAll('[data-k]').forEach(x=>o[x.dataset.k]=Number(x.value));if(Object.values(o).some(x=>!Number.isInteger(x)||x<1||x>100))return alert('各項目に1〜100の整数を入力してください。');state.settings.reviewIntervals=o;save();alert('設定を保存しました。')};$('#def').onclick=()=>confirm('復習間隔を初期値に戻しますか？','初期値に戻す',()=>{state.settings.reviewIntervals={...DEF};save();settings()});$('#clear').onclick=()=>confirm('すべての学習履歴・復習キュー・設定をリセットしますか？','すべてリセット',()=>{localStorage.removeItem(KEY);state=init();home()})}
  function confirm(msg,label,ok){document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="modal"><div class="modal-box"><h3>確認</h3><p>${msg}</p><div class="modal-actions">${btn('キャンセル','btn btn-outline','id="cancel"')}${btn(label,'btn btn-danger','id="yes"')}</div></div></div>`);$('#cancel').onclick=()=>$('#modal').remove();$('#yes').onclick=()=>{$('#modal').remove();ok()}}
  home();
})();
